parameters:
#    portfolio_folio.example.class: Portfolio\FolioBundle\Example

services:
#    portfolio_folio.example:
#        class: %portfolio_folio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
